function draw_style(ax)
%DRAW_STYLE  ChemMate 统一坐标轴风格
%   所有 plot_*.m 共用：统一字体 / 线宽 / 边框 / 刻度方向 / 淡色网格，
%   保证四类图长成一套风格。

    if nargin < 1 || isempty(ax)
        ax = gca;   % 未指定坐标轴时使用当前坐标轴
    end
    % 基础样式：Arial 11pt、细线框、刻度朝外
    set(ax, ...
        'FontName', 'Arial', ...
        'FontSize', 11, ...
        'LineWidth', 1.0, ...
        'Box', 'on', ...
        'TickDir', 'out', ...
        'XColor', [0.15 0.15 0.15], ...
        'YColor', [0.15 0.15 0.15]);
    % 淡色虚线网格：方便读数，又不抢数据本身
    grid(ax, 'on');
    set(ax, 'GridLineStyle', ':', 'GridAlpha', 0.35, 'GridColor', [0.4 0.4 0.4]);
end
